# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ecfault.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\recfault.proto\x12\x07\x65\x63\x66\x61ult\"\x1b\n\x07\x44\x65vInfo\x12\x10\n\x08\x64\x65v_info\x18\x01 \x03(\t\"v\n\x0bVirtDevInfo\x12\x15\n\x08\x64\x65v_path\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07\x62k_path\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x12\n\nbk_per_dev\x18\x03 \x01(\x05\x12\r\n\x05\x62k_sz\x18\x04 \x01(\x05\x42\x0b\n\t_dev_pathB\n\n\x08_bk_path\"l\n\x13VirtDevInfoMultiple\x12\x10\n\x08\x64\x65v_path\x18\x01 \x03(\t\x12\x14\n\x07\x62k_path\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x12\n\nbk_per_dev\x18\x03 \x01(\x05\x12\r\n\x05\x62k_sz\x18\x04 \x01(\x05\x42\n\n\x08_bk_path\"\x14\n\x04Stat\x12\x0c\n\x04stat\x18\x01 \x01(\x05\"\x19\n\x0bPlaceholder\x12\n\n\x02op\x18\x01 \x01(\x05\"\x1d\n\x0bSystemStats\x12\x0e\n\x06health\x18\x01 \x01(\x05\"\x1b\n\tNodeStats\x12\x0e\n\x06health\x18\x01 \x01(\x05\"*\n\x05\x46\x61ult\x12!\n\x05\x66\x61ult\x18\x01 \x01(\x0e\x32\x12.ecfault.FaultType*,\n\tFaultType\x12\t\n\x05\x42LOCK\x10\x00\x12\n\n\x06\x44\x45VICE\x10\x01\x12\x08\n\x04NODE\x10\x02\x32\x89\x02\n\rRemoteNVMeDev\x12\x39\n\rget_avail_dev\x12\x14.ecfault.Placeholder\x1a\x10.ecfault.DevInfo\"\x00\x12\x38\n\x0fnvme_dev_create\x12\x14.ecfault.VirtDevInfo\x1a\r.ecfault.Stat\"\x00\x12I\n\x18nvme_dev_create_multiple\x12\x1c.ecfault.VirtDevInfoMultiple\x1a\r.ecfault.Stat\"\x00\x12\x38\n\x0fnvme_dev_remove\x12\x14.ecfault.Placeholder\x1a\r.ecfault.Stat\"\x00\x32\x8f\x01\n\tStatQuery\x12\x42\n\x12system_stats_query\x12\x14.ecfault.Placeholder\x1a\x14.ecfault.SystemStats\"\x00\x12>\n\x10node_stats_query\x12\x14.ecfault.Placeholder\x1a\x12.ecfault.NodeStats\"\x00\x32\x41\n\x0e\x46\x61ultInjection\x12/\n\x0cinject_fault\x12\x0e.ecfault.Fault\x1a\r.ecfault.Stat\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ecfault_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_FAULTTYPE']._serialized_start=438
  _globals['_FAULTTYPE']._serialized_end=482
  _globals['_DEVINFO']._serialized_start=26
  _globals['_DEVINFO']._serialized_end=53
  _globals['_VIRTDEVINFO']._serialized_start=55
  _globals['_VIRTDEVINFO']._serialized_end=173
  _globals['_VIRTDEVINFOMULTIPLE']._serialized_start=175
  _globals['_VIRTDEVINFOMULTIPLE']._serialized_end=283
  _globals['_STAT']._serialized_start=285
  _globals['_STAT']._serialized_end=305
  _globals['_PLACEHOLDER']._serialized_start=307
  _globals['_PLACEHOLDER']._serialized_end=332
  _globals['_SYSTEMSTATS']._serialized_start=334
  _globals['_SYSTEMSTATS']._serialized_end=363
  _globals['_NODESTATS']._serialized_start=365
  _globals['_NODESTATS']._serialized_end=392
  _globals['_FAULT']._serialized_start=394
  _globals['_FAULT']._serialized_end=436
  _globals['_REMOTENVMEDEV']._serialized_start=485
  _globals['_REMOTENVMEDEV']._serialized_end=750
  _globals['_STATQUERY']._serialized_start=753
  _globals['_STATQUERY']._serialized_end=896
  _globals['_FAULTINJECTION']._serialized_start=898
  _globals['_FAULTINJECTION']._serialized_end=963
# @@protoc_insertion_point(module_scope)
